Disable ceph-csi and default storageclasses on provider deployment
red-hat-storage/ocs-osd-deployer pull request #133
Opened 2022-03-09 11:04 UTC by bindrad

Signed-off-by: bindrad <dbindra@redhat.com>

2022-03-09 11:13 UTC, nb-ohad requested changes

2022-03-09 11:13 UTC, nb-ohad commented on controllers/managedocs_controller.go
>  		}
The code for both helpers seems almost identical and is not predicated to diverge any further in the future. 
Can we just solve it with a simple if inside the original `reconcileRookCephOperatorConfig` func?

2022-03-10 09:49 UTC, Madhu-1 commented on controllers/managedocs_controller.go
> +			rookConfigMap.Data["ROOK_CSI_ENABLE_RBD"] != "false" {
why this check is required? you can directly assign "false" value if it's a providerDeploymentType?

2022-03-10 18:57 UTC, nb-ohad approved these changes

2022-03-11 08:12 UTC, merged